### ISSUE TITLE
Process problem

### ISSUE THREAD

**Issue by omertrans678** [SmoLL-iCe/DotNetAobScanMemory#3]
I wrote trial.bin and tried it. gave an error. I tried Trial.exe, it worked.
Please how use trial.bin process
dont work to code:   Dim p = Process.GetProcessesByName("trial")

**Comment by SmoLL-iCe** [comment]
this problem is not caused by the fault of this project, this is a problem of the .net itself in its class of processes.
by default he tries to filter those ending with the .exe extension. 

you can do it as follows if you prefer.
why then he will list and search for one that partially contains the name he wants. 
```vb
    Function get_process_by_name(ByVal p_name As String) As Process
        Dim rp As Process = Nothing
        Dim all_processes As Process() = Process.GetProcesses()
        For Each p In all_processes
            If p.ProcessName.Contains(p_name) Then
                Return p
            End If
        Next
        Return rp
    End Function
```

this project in itself gives you the freedom to capture the process yourself and go through the argument in any way you want. 
```vb
Dim find_aob As New dotNetMemoryScan()
Dim p As Process = get_process_by_name("explorer")
If Not IsNothing(p) Then
    Dim find_ptr = find_aob.scan_all(p.Handle, "83 05 ?? ?? ?? ?? 0A A1")
'.............
End If
```

**Comment by omertrans678** [comment]
Thanks you ❤️
